// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/empovit/assisted-agent-simulator/service/models"
)

// GetInstructionsOKCode is the HTTP code returned for type GetInstructionsOK
const GetInstructionsOKCode int = 200

/*GetInstructionsOK Success.

swagger:response getInstructionsOK
*/
type GetInstructionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Step `json:"body,omitempty"`
}

// NewGetInstructionsOK creates GetInstructionsOK with default headers values
func NewGetInstructionsOK() *GetInstructionsOK {

	return &GetInstructionsOK{}
}

// WithPayload adds the payload to the get instructions o k response
func (o *GetInstructionsOK) WithPayload(payload *models.Step) *GetInstructionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get instructions o k response
func (o *GetInstructionsOK) SetPayload(payload *models.Step) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInstructionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetInstructionsInternalServerErrorCode is the HTTP code returned for type GetInstructionsInternalServerError
const GetInstructionsInternalServerErrorCode int = 500

/*GetInstructionsInternalServerError Unexpected error

swagger:response getInstructionsInternalServerError
*/
type GetInstructionsInternalServerError struct {
}

// NewGetInstructionsInternalServerError creates GetInstructionsInternalServerError with default headers values
func NewGetInstructionsInternalServerError() *GetInstructionsInternalServerError {

	return &GetInstructionsInternalServerError{}
}

// WriteResponse to the client
func (o *GetInstructionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetInstructionsNotImplementedCode is the HTTP code returned for type GetInstructionsNotImplemented
const GetInstructionsNotImplementedCode int = 501

/*GetInstructionsNotImplemented Not implemented

swagger:response getInstructionsNotImplemented
*/
type GetInstructionsNotImplemented struct {
}

// NewGetInstructionsNotImplemented creates GetInstructionsNotImplemented with default headers values
func NewGetInstructionsNotImplemented() *GetInstructionsNotImplemented {

	return &GetInstructionsNotImplemented{}
}

// WriteResponse to the client
func (o *GetInstructionsNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(501)
}
