// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// InstructionsHandlerFunc turns a function with the right signature into a instructions handler
type InstructionsHandlerFunc func(InstructionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn InstructionsHandlerFunc) Handle(params InstructionsParams) middleware.Responder {
	return fn(params)
}

// InstructionsHandler interface for that can handle valid instructions params
type InstructionsHandler interface {
	Handle(InstructionsParams) middleware.Responder
}

// NewInstructions creates a new http.Handler for the instructions operation
func NewInstructions(ctx *middleware.Context, handler InstructionsHandler) *Instructions {
	return &Instructions{Context: ctx, Handler: handler}
}

/*Instructions swagger:route GET /instructions instructions

Returns a command to be run by the agent

*/
type Instructions struct {
	Context *middleware.Context
	Handler InstructionsHandler
}

func (o *Instructions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewInstructionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
