// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/empovit/assisted-agent-simulator/service/models"
)

// InstructionsOKCode is the HTTP code returned for type InstructionsOK
const InstructionsOKCode int = 200

/*InstructionsOK Success.

swagger:response instructionsOK
*/
type InstructionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Step `json:"body,omitempty"`
}

// NewInstructionsOK creates InstructionsOK with default headers values
func NewInstructionsOK() *InstructionsOK {

	return &InstructionsOK{}
}

// WithPayload adds the payload to the instructions o k response
func (o *InstructionsOK) WithPayload(payload *models.Step) *InstructionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the instructions o k response
func (o *InstructionsOK) SetPayload(payload *models.Step) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InstructionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InstructionsInternalServerErrorCode is the HTTP code returned for type InstructionsInternalServerError
const InstructionsInternalServerErrorCode int = 500

/*InstructionsInternalServerError Unexpected error

swagger:response instructionsInternalServerError
*/
type InstructionsInternalServerError struct {
}

// NewInstructionsInternalServerError creates InstructionsInternalServerError with default headers values
func NewInstructionsInternalServerError() *InstructionsInternalServerError {

	return &InstructionsInternalServerError{}
}

// WriteResponse to the client
func (o *InstructionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
