swagger: "2.0"
info:
  description: Server side of agent simulator
  version: 1.0.0
  title: Agent Simulator
host: localhost
basePath: /

schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /instructions:
    get:
      summary: Returns a command to be run by the agent
      responses:
        200:
          description: Success.
          schema:
            $ref: '#/definitions/step'            
        500:
          description: Unexpected error
        501:
          description: Not implemented

definitions:
  step:
    type: object
    properties:
      command:
        type: string
      args:
        type: array
        items:
          type: string