// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCommandsHandlerFunc turns a function with the right signature into a get commands handler
type GetCommandsHandlerFunc func(GetCommandsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCommandsHandlerFunc) Handle(params GetCommandsParams) middleware.Responder {
	return fn(params)
}

// GetCommandsHandler interface for that can handle valid get commands params
type GetCommandsHandler interface {
	Handle(GetCommandsParams) middleware.Responder
}

// NewGetCommands creates a new http.Handler for the get commands operation
func NewGetCommands(ctx *middleware.Context, handler GetCommandsHandler) *GetCommands {
	return &GetCommands{Context: ctx, Handler: handler}
}

/*GetCommands swagger:route GET /commands getCommands

Returns a command to be run by the agent

*/
type GetCommands struct {
	Context *middleware.Context
	Handler GetCommandsHandler
}

func (o *GetCommands) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCommandsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
