// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/empovit/assisted-agent-simulator/server/models"
)

// GetCommandsOKCode is the HTTP code returned for type GetCommandsOK
const GetCommandsOKCode int = 200

/*GetCommandsOK Success.

swagger:response getCommandsOK
*/
type GetCommandsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Command `json:"body,omitempty"`
}

// NewGetCommandsOK creates GetCommandsOK with default headers values
func NewGetCommandsOK() *GetCommandsOK {

	return &GetCommandsOK{}
}

// WithPayload adds the payload to the get commands o k response
func (o *GetCommandsOK) WithPayload(payload *models.Command) *GetCommandsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get commands o k response
func (o *GetCommandsOK) SetPayload(payload *models.Command) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommandsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCommandsNotFoundCode is the HTTP code returned for type GetCommandsNotFound
const GetCommandsNotFoundCode int = 404

/*GetCommandsNotFound Not found

swagger:response getCommandsNotFound
*/
type GetCommandsNotFound struct {
}

// NewGetCommandsNotFound creates GetCommandsNotFound with default headers values
func NewGetCommandsNotFound() *GetCommandsNotFound {

	return &GetCommandsNotFound{}
}

// WriteResponse to the client
func (o *GetCommandsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetCommandsInternalServerErrorCode is the HTTP code returned for type GetCommandsInternalServerError
const GetCommandsInternalServerErrorCode int = 500

/*GetCommandsInternalServerError Unexpected error

swagger:response getCommandsInternalServerError
*/
type GetCommandsInternalServerError struct {
}

// NewGetCommandsInternalServerError creates GetCommandsInternalServerError with default headers values
func NewGetCommandsInternalServerError() *GetCommandsInternalServerError {

	return &GetCommandsInternalServerError{}
}

// WriteResponse to the client
func (o *GetCommandsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetCommandsNotImplementedCode is the HTTP code returned for type GetCommandsNotImplemented
const GetCommandsNotImplementedCode int = 501

/*GetCommandsNotImplemented Not implemented

swagger:response getCommandsNotImplemented
*/
type GetCommandsNotImplemented struct {
}

// NewGetCommandsNotImplemented creates GetCommandsNotImplemented with default headers values
func NewGetCommandsNotImplemented() *GetCommandsNotImplemented {

	return &GetCommandsNotImplemented{}
}

// WriteResponse to the client
func (o *GetCommandsNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(501)
}
