// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstructionsParams creates a new GetInstructionsParams object
// with the default values initialized.
func NewGetInstructionsParams() *GetInstructionsParams {

	return &GetInstructionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstructionsParamsWithTimeout creates a new GetInstructionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInstructionsParamsWithTimeout(timeout time.Duration) *GetInstructionsParams {

	return &GetInstructionsParams{

		timeout: timeout,
	}
}

// NewGetInstructionsParamsWithContext creates a new GetInstructionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInstructionsParamsWithContext(ctx context.Context) *GetInstructionsParams {

	return &GetInstructionsParams{

		Context: ctx,
	}
}

// NewGetInstructionsParamsWithHTTPClient creates a new GetInstructionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInstructionsParamsWithHTTPClient(client *http.Client) *GetInstructionsParams {

	return &GetInstructionsParams{
		HTTPClient: client,
	}
}

/*GetInstructionsParams contains all the parameters to send to the API endpoint
for the get instructions operation typically these are written to a http.Request
*/
type GetInstructionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get instructions params
func (o *GetInstructionsParams) WithTimeout(timeout time.Duration) *GetInstructionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instructions params
func (o *GetInstructionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instructions params
func (o *GetInstructionsParams) WithContext(ctx context.Context) *GetInstructionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instructions params
func (o *GetInstructionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instructions params
func (o *GetInstructionsParams) WithHTTPClient(client *http.Client) *GetInstructionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instructions params
func (o *GetInstructionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstructionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
