// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/empovit/assisted-agent-simulator/service/models"
)

// InstructionsReader is a Reader for the Instructions structure.
type InstructionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstructionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInstructionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewInstructionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInstructionsOK creates a InstructionsOK with default headers values
func NewInstructionsOK() *InstructionsOK {
	return &InstructionsOK{}
}

/*InstructionsOK handles this case with default header values.

Success.
*/
type InstructionsOK struct {
	Payload *models.Step
}

func (o *InstructionsOK) Error() string {
	return fmt.Sprintf("[GET /instructions][%d] instructionsOK  %+v", 200, o.Payload)
}

func (o *InstructionsOK) GetPayload() *models.Step {
	return o.Payload
}

func (o *InstructionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Step)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInstructionsInternalServerError creates a InstructionsInternalServerError with default headers values
func NewInstructionsInternalServerError() *InstructionsInternalServerError {
	return &InstructionsInternalServerError{}
}

/*InstructionsInternalServerError handles this case with default header values.

Unexpected error
*/
type InstructionsInternalServerError struct {
}

func (o *InstructionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /instructions][%d] instructionsInternalServerError ", 500)
}

func (o *InstructionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
