// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInstructionsParams creates a new InstructionsParams object
// with the default values initialized.
func NewInstructionsParams() *InstructionsParams {

	return &InstructionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInstructionsParamsWithTimeout creates a new InstructionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInstructionsParamsWithTimeout(timeout time.Duration) *InstructionsParams {

	return &InstructionsParams{

		timeout: timeout,
	}
}

// NewInstructionsParamsWithContext creates a new InstructionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewInstructionsParamsWithContext(ctx context.Context) *InstructionsParams {

	return &InstructionsParams{

		Context: ctx,
	}
}

// NewInstructionsParamsWithHTTPClient creates a new InstructionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInstructionsParamsWithHTTPClient(client *http.Client) *InstructionsParams {

	return &InstructionsParams{
		HTTPClient: client,
	}
}

/*InstructionsParams contains all the parameters to send to the API endpoint
for the instructions operation typically these are written to a http.Request
*/
type InstructionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the instructions params
func (o *InstructionsParams) WithTimeout(timeout time.Duration) *InstructionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the instructions params
func (o *InstructionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the instructions params
func (o *InstructionsParams) WithContext(ctx context.Context) *InstructionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the instructions params
func (o *InstructionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the instructions params
func (o *InstructionsParams) WithHTTPClient(client *http.Client) *InstructionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the instructions params
func (o *InstructionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *InstructionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
